# Generated by Django 4.0.4 on 2022-07-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(max_length=100)),
                ('fact1', models.CharField(max_length=100)),
                ('pickup_line', models.CharField(max_length=100)),
            ],
        ),
    ]
